version: '3'
services:
  frontend:
    image: akhilpuppala/frontend-image:latest
    restart: always
    ports:
      - '3000:3000'
    command: npm start  # Use "npm run dev" if you prefer

  backend:
    image: akhilpuppala/backend-image:latest
    restart: always
    ports:
      - '5000:5000'
    environment:
      - mongo_url=mongodb+srv://AkhilPuppala:Akhil1203@cluster0.e6z5o.mongodb.net/foodDB
    depends_on:
      - mongodb  # Optional, only if you want to connect to a local MongoDB instance

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
