version: '3'
services:
  frontend:
    image: akhilpuppala/frontend-image:latest
    restart: always
    ports:
      - '3000:3000'
    command: npm start  # Use "npm run dev" if you prefer

  backend:
    image: akhilpuppala/backend-image:latest
    restart: always
    ports:
      - '5000:5000'
    environment:
      - mongo_url=mongodb://mongodb:27017/foodDB
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
