version: '3'
services:
  frontend:
    image: akhilpuppala/frontend-image:latest
    restart: always
    ports:
      - '3000:3000'
  backend:
    image: akhilpuppala/backend-image:latest
    restart: always
    ports:
      - '5000:5000'
    environment:
      - mongo_url=mongodb+srv://AkhilPuppala:umLsSsfuRrLfithN@cluster0.e6z5o.mongodb.net/foodDB  
